export default function KeyValRow(props) {
    console.log(props);
    return React.createElement(
        "tr",
        null,
        React.createElement(
            "td",
            null,
            props.id
        ),
        React.createElement(
            "td",
            null,
            props.k
        ),
        React.createElement(
            "td",
            null,
            props.value
        ),
        React.createElement(
            "td",
            null,
            props.expire_on
        ),
        React.createElement(
            "td",
            null,
            React.createElement(
                "button",
                null,
                ":)"
            )
        )
    );
}